spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tbl_video_catalog
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1