server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

video:
  directory:
    path: D:\Code\Java\Spring\spring-microservices-video-streaming-app\videos\

video-catalog-service:
  url: http://video-catalog

management:
  tracing:
    sampling:
      probability: 1