spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: D:\\Code\\Java\\Spring\\spring-microservices-video-streaming-app\\config
  profiles:
    active: native

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
